using System;

namespace WSGM.Device.Contracts.Ipc;

/// <summary>
/// The protocol versions this build speaks, and how a version is agreed with a peer.
/// </summary>
/// <remarks>
/// A compatibility window rather than a single version, so a WSGM update and a plugin update do not
/// have to ship together. The window is deliberately narrow: every version inside it must be kept
/// working and tested, so widening it is a maintenance commitment rather than a courtesy.
/// </remarks>
public static class DeviceProtocol
{
    /// <summary>Oldest protocol version this build can speak.</summary>
    public const ushort MinSupportedVersion = 1;

    /// <summary>Newest protocol version this build can speak.</summary>
    public const ushort MaxSupportedVersion = 1;

    /// <summary>
    /// A fingerprint of the contract shapes this build compiles against.
    /// </summary>
    /// <remarks>
    /// Two builds can agree on a version number and still disagree about what a message contains, if
    /// one of them changed a contract without bumping the version. The fingerprint catches that: it
    /// is compared during the handshake, and a mismatch refuses the connection rather than letting
    /// two peers misread each other's payloads.
    /// </remarks>
    public const string SchemaFingerprint = "wsgm-device-v1";

    /// <summary>
    /// Picks the version two peers should use.
    /// </summary>
    /// <param name="peerMin">Oldest version the peer supports.</param>
    /// <param name="peerMax">Newest version the peer supports.</param>
    /// <param name="peerFingerprint">The peer's schema fingerprint.</param>
    /// <param name="negotiated">The agreed version, when the result is <see cref="NegotiationResult.Agreed"/>.</param>
    /// <returns>Whether a version was agreed, and why not when it was not.</returns>
    /// <remarks>
    /// The highest version both sides support wins, so two current builds never fall back to an older
    /// encoding just because the window includes one.
    /// </remarks>
    public static NegotiationResult Negotiate(
        ushort peerMin,
        ushort peerMax,
        string peerFingerprint,
        out ushort negotiated)
    {
        negotiated = 0;

        if (peerMin > peerMax)
        {
            return NegotiationResult.MalformedRange;
        }

        ushort low = Math.Max(peerMin, MinSupportedVersion);
        ushort high = Math.Min(peerMax, MaxSupportedVersion);

        if (low > high)
        {
            return peerMax < MinSupportedVersion
                ? NegotiationResult.PeerTooOld
                : NegotiationResult.PeerTooNew;
        }

        // Checked after the version overlap, so a peer inside the window with a changed contract
        // reports the fingerprint mismatch rather than a misleading version error.
        if (!string.Equals(peerFingerprint, SchemaFingerprint, StringComparison.Ordinal))
        {
            return NegotiationResult.SchemaMismatch;
        }

        negotiated = high;
        return NegotiationResult.Agreed;
    }
}

/// <summary>The outcome of protocol negotiation.</summary>
public enum NegotiationResult
{
    /// <summary>A version was agreed.</summary>
    Agreed,

    /// <summary>The peer supports only versions older than this build.</summary>
    PeerTooOld,

    /// <summary>The peer supports only versions newer than this build.</summary>
    PeerTooNew,

    /// <summary>The peer sent an inverted version range.</summary>
    MalformedRange,

    /// <summary>Versions overlap but the contract shapes differ.</summary>
    SchemaMismatch,
}

/// <summary>
/// How the control endpoint is named and secured.
/// </summary>
/// <remarks>
/// A named pipe rather than localhost TCP. A TCP listener is reachable by every process on the
/// machine and by anything that can talk to the loopback interface, and securing it would mean
/// inventing an authentication scheme; a named pipe carries an ACL the operating system enforces
/// before a single byte is read.
/// </remarks>
public static class ControlEndpoint
{
    /// <summary>Length of the handshake nonce in bytes.</summary>
    public const int NonceBytes = 32;

    /// <summary>
    /// Builds the pipe name for one session and host instance.
    /// </summary>
    /// <param name="sessionId">The interactive session identifier.</param>
    /// <param name="instanceToken">
    /// A token unique to this host launch, generated by WSGM and passed to the host at spawn.
    /// </param>
    /// <returns>The pipe name, without the leading path.</returns>
    /// <remarks>
    /// Scoped per session so two interactive sessions never share an endpoint, and per launch so a
    /// stale host cannot occupy the name a new one expects. The instance token is passed to the host
    /// as a spawn argument, which is what binds the connection to a host WSGM actually started —
    /// another process on the machine can connect to a pipe, but cannot know the name.
    /// </remarks>
    public static string PipeName(uint sessionId, string instanceToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(instanceToken);
        return $"WSGM.DeviceHost.{sessionId}.{instanceToken}";
    }

    /// <summary>
    /// Whether a handshake nonce is acceptable.
    /// </summary>
    /// <param name="nonce">The nonce presented by the peer.</param>
    /// <param name="expected">The nonce WSGM generated for this host.</param>
    /// <returns><see langword="true"/> when the nonce matches.</returns>
    /// <remarks>
    /// Compared in constant time over the full length. A short-circuiting comparison leaks how many
    /// leading bytes were right, which turns guessing the nonce into a per-byte search.
    /// </remarks>
    public static bool NonceMatches(ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> expected)
    {
        if (nonce.Length != expected.Length || nonce.Length != NonceBytes)
        {
            return false;
        }

        int difference = 0;
        for (int i = 0; i < nonce.Length; i++)
        {
            difference |= nonce[i] ^ expected[i];
        }

        return difference == 0;
    }
}
