<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>WSGM.DeviceLab</AssemblyName>
    <RootNamespace>WSGM.DeviceLab.Gui</RootNamespace>
    <SelfContained>true</SelfContained>
    <PublishAot>false</PublishAot>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WSGM.DeviceLab.Core\WSGM.DeviceLab.Core.csproj" />
  </ItemGroup>
</Project>
