<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\WSGM\Assets\wsgm.ico</ApplicationIcon>
    <AssemblyName>WSGM.Explorerfy</AssemblyName>
    <RootNamespace>WSGM.Explorerfy</RootNamespace>
    <PublishAot>true</PublishAot>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
